// <auto-generated />
using FuzzyLogicInterface.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuzzyLogicInterface.Migrations
{
    [DbContext(typeof(FuzzyContext))]
    [Migration("20220812122408_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FuzzyLogicInterface.Models.RuleCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCoverage")
                        .HasColumnType("int");

                    b.Property<float>("CriticalityOfRequirement")
                        .HasColumnType("real");

                    b.Property<float>("FaultCoverage")
                        .HasColumnType("real");

                    b.Property<int>("ModuleCodeLines")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriorityValue")
                        .HasColumnType("real");

                    b.Property<int>("RecordNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InputData");
                });
#pragma warning restore 612, 618
        }
    }
}
