// <auto-generated />
using System;
using FuzzyLogicInterface.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuzzyLogicInterface.Migrations
{
    [DbContext(typeof(FuzzyContext))]
    partial class FuzzyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FuzzyLogicInterface.Models.ModuleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndSession")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleCodeLines")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartSession")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ModulesData");
                });

            modelBuilder.Entity("FuzzyLogicInterface.Models.TestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("CodeCoverage")
                        .HasColumnType("real");

                    b.Property<float>("CriticalityOfRequirement")
                        .HasColumnType("real");

                    b.Property<float>("FaultCoverage")
                        .HasColumnType("real");

                    b.Property<int>("ModuleCodeLinesEntered")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriorityValue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TestsData");
                });
#pragma warning restore 612, 618
        }
    }
}
